name: Crystal CI
on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: crystallang/crystal
    steps:
    - uses: actions/checkout@v4
    - name: Install 
      run:  install Shard
    - name: Run tests
      run: crystal spec
